"""Focused regression tests for Agent 6 deterministic decision synthesis."""

from app.services.agent6_decision import Agent6Recommend
from app.services.investigation_context import InvestigationContext


def make_ctx(prob=0.2, evidence=0.8, network=None, regulatory=None):
    ctx = InvestigationContext("txn-1", {
        "_id": "txn-1",
        "account_id": "ACC-1",
        "counterpartyAccount": "ACC-2",
        "timestamp": "2026-01-01T12:00:00+00:00",
    })
    ctx.anomaly_scores = {"probability": prob, "risk_level": "high" if prob >= .65 else "low"}
    ctx.evidence = {"evidence_confidence": evidence, "patterns": []}
    ctx.network = network or {}
    ctx.regulatory = regulatory or {}
    return ctx


def run(ctx):
    return Agent6Recommend().run(ctx).recommendation


def test_basic_low_risk_closes():
    rec = run(make_ctx(.10, .90))
    assert rec["action"] == "CLOSE"
    assert rec["decision"] == "CLOSE"


def test_high_fraud_with_weak_evidence_requests_information():
    rec = run(make_ctx(.90, .30))
    assert rec["action"] == "REQUEST_INFO"
    assert rec["priority"] == "high"


def test_high_fraud_with_strong_evidence_escalates():
    rec = run(make_ctx(.90, .80))
    assert rec["action"] == "ESCALATE"


def test_high_network_risk_beats_large_node_count():
    low_risk_large = run(make_ctx(.20, .80, {"node_count": 10, "evidence": {"provisional_network_risk_score": .20}}))
    high_risk_small = run(make_ctx(.20, .80, {"node_count": 3, "evidence": {"provisional_network_risk_score": .85}}))
    assert low_risk_large["action"] == "CLOSE"
    assert high_risk_small["action"] == "ESCALATE"


def test_agent4_str_review_is_routed_without_claiming_filing():
    rec = run(make_ctx(.50, .80, regulatory={
        "risk_score": .80,
        "reportability_assessment": {"status": "STR_REVIEW_RECOMMENDED", "recommendation": "REVIEW_FOR_STR"},
        "str_assessment": {"recommendation": "REVIEW_FOR_STR", "confidence": .85},
    }))
    assert rec["action"] == "FILE_STR"
    assert rec["str_status"] == "REVIEW_RECOMMENDED"
    assert "not_filed" in rec["case_action"]
    assert "filed" not in rec["reasoning"].lower()


def test_agent4_not_enough_evidence_never_creates_str_decision():
    rec = run(make_ctx(.90, .40, regulatory={
        "risk_score": .80,
        "reportability_assessment": {"status": "NOT_ENOUGH_EVIDENCE", "recommendation": "NO_STR_RECOMMENDATION"},
        "str_assessment": {"recommendation": "NO_STR_RECOMMENDATION", "confidence": .35},
    }))
    assert rec["action"] == "REQUEST_INFO"
    assert rec["action"] != "FILE_STR"


def test_agent4_further_review_is_preserved():
    rec = run(make_ctx(.70, .70, regulatory={
        "reportability_assessment": {"status": "FURTHER_REVIEW_REQUIRED", "recommendation": "FURTHER_REVIEW"},
        "str_assessment": {"recommendation": "FURTHER_REVIEW", "confidence": .60},
    }))
    assert rec["action"] == "REQUEST_INFO"
    assert rec["str_status"] == "FURTHER_REVIEW"


def test_missing_upstream_data_is_explicit():
    ctx = InvestigationContext("txn-2", {})
    rec = run(ctx)
    assert rec["action"] == "CLOSE"
    assert rec["requires_human_review"] is True
    assert rec["missing_information"]
    assert rec["regulatory_assessment"] == {}


def test_watchlist_requires_supporting_signals():
    ctx = make_ctx(.55, .80)
    ctx.watchlist_hit = True
    rec = run(ctx)
    assert rec["action"] == "BLOCK"
    assert rec["priority"] == "critical"


def test_disagreement_escalates():
    ctx = make_ctx(.45, .80)
    ctx.disagreement_flag = True
    rec = run(ctx)
    assert rec["action"] == "ESCALATE"
    assert rec["requires_human_review"] is True


def test_deterministic_output_for_same_context():
    a = run(make_ctx(.55, .80, {"node_count": 3, "evidence": {"provisional_network_risk_score": .60}}))
    b = run(make_ctx(.55, .80, {"node_count": 3, "evidence": {"provisional_network_risk_score": .60}}))
    # Ignore the legacy timestamps generated by InvestigationContext.set_recommendation.
    for rec in (a, b):
        rec.pop("timestamp", None)
    assert a == b


def test_malformed_numeric_values_do_not_crash():
    ctx = InvestigationContext("txn-3", {})
    ctx.anomaly_scores = {"probability": "not-a-number"}
    ctx.evidence = {"evidence_confidence": None}
    ctx.network = {"node_count": "bad", "evidence": {"provisional_network_risk_score": "bad"}}
    ctx.regulatory = {"risk_score": "bad"}
    rec = run(ctx)
    assert rec["action"] == "CLOSE"
    assert rec["decision"] == "CLOSE"
